config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: { registrations: 'registrations' }
  root 'employees#index'

  resources :employees, only: [:index]

  namespace :admin do
    resources :departments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  belongs_to :department
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_employee!
  before_action :check_admin

  layout "admin"

  protected

  def check_admin
    redirect_to employees_path, notice: "У Вас немає прав доступу до даної сторінки" unless current_employee.admin?
  end
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < Admin::AdminController
  before_action :set_department, only: %i[show edit update destroy]

  def index
    @departments = Department.all.page(params[:page]).per(2)
  end

  def show; end

  def new
    @department = Department.new
  end

  def edit; end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to admin_departments_path, success: 'Department was successfully created.'
    else
      render :new
    end
  end

  def update
    if @department.update(department_params)
      redirect_to admin_departments_path, success: 'Department was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to admin_departments_path, success: 'Department was successfully destroyed.'
  end

  private

  def set_department
    @department = Department.find(params[:id])
  end

  def department_params
    params.require(:department).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name department_id email active
                                                         password password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[email password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name department_id active])
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[show edit update destroy]

  def index
    @departments = Department.all
  end

  def show; end

  def new
    @department = Department.new
  end

  def edit; end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to @department, notice: 'Department was successfully created.'
    else
      render :new
    end
  end

  def update
    if @department.update(department_params)
      redirect_to @department, notice: 'Department was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path, notice: 'Department was successfully destroyed.'
  end

  private

  def set_department
    @department = Department.find(params[:id])
  end

  def department_params
    params.require(:department).permit(:name)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all.page(params[:page]).per(2)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/departments/_form.html.haml
= form_for [:admin, @department] do |f|
  .form-group
    = f.label :name
    = f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control'
  .actions
    = link_to 'Back', :back, class: 'btn btn-danger pull-left'
    = f.submit "Create", class: 'btn btn-primary'

app/views/admin/departments/edit.html.haml
%h2= "Edit department"

= render 'form', department: @department

app/views/admin/departments/index.html.haml
%h2= "All departments"
= link_to 'New Department', new_admin_department_path
%p#notice= notice

.row
  .col-md-12
    .table-responsive
      %table.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th= "ID"
            %th= "Name"
            %th= "Actions"

        %tbody
          - @departments.each do |department|
            %tr
              %td= department.id
              %td= department.name
              %td
                %a= link_to "Edit", edit_admin_department_path(department)
                %a= link_to "Delete", [:admin, department], data: { confirm: "Are you sure" }, method: :delete

=paginate @departments

app/views/admin/departments/new.html.haml
%h2= "New Department"

=render "form"

app/views/employees/index.html.haml
%h2= "All employees"
%p#notice= notice

.row
  .col-md-12
    .table-responsive
      %table.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th= "ID"
            %th= "Name"
            %th= "Active"
            %th= "Department"
            %th= "Actions"

        %tbody
          - @employees.each do |employee|
            %tr
              %td= employee.id
              %td= employee.name
              %td= employee.active == true ? "Yes" : "No"
              %td= employee.department.name
              %td
                %a= link_to "Edit", edit_employee_registration_path(employee)
                %a= link_to "Delete", employees_path, data: { confirm: "Are you sure" }, method: :delete

= paginate @employees

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestTask</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="#"><%= "Admin Panel" %></a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= 'active' if current_page?(root_path) || current_page?(employees_path) %> ">
          <a class="nav-link" href="<%= employees_path %>"><%= "All employees" %> <span class="sr-only">(current)</span></a>
        </li>
        <% if employee_signed_in? && current_employee.admin? %>
          <li class="nav-item <%= 'active' if current_page?(root_path) || current_page?(admin_departments_path) %> ">
            <a class="nav-link" href="<%= admin_departments_path %>"><%= "All departments" %> <span class="sr-only">(current)</span></a>
          </li>
        <% end %>
      </ul>
    </div>

    <div>
      <ul class="navbar-nav mr-auto">
        <% if employee_signed_in? %>
          <li class="nav-item <%= 'active' if current_page?(destroy_employee_session_path) %> ">
            <%= link_to t("common.sign_out"), destroy_employee_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item <%= 'active' if current_page?(new_employee_session_path) %> ">
            <%= link_to t("common.log_in"), new_employee_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(new_employee_registration_path) %> ">
            <%= link_to t("common.sign_up"), new_employee_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <a class="navbar-brand" href="#"><%= "Test Task" %></a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item <%= 'active' if current_page?(root_path) || current_page?(employees_path) %> ">
              <a class="nav-link" href="<%= employees_path %>"><%= "All employees" %> <span class="sr-only">(current)</span></a>
            </li>
            <% if employee_signed_in? && current_employee.admin? %>
              <li class="nav-item <%= 'active' if current_page?(root_path) || current_page?(admin_departments_path) %> ">
                <a class="nav-link" href="<%= admin_departments_path %>"><%= "All departments" %> <span class="sr-only">(current)</span></a>
              </li>
            <% end %>
          </ul>
        </div>

        <div>
          <ul class="navbar-nav mr-auto">
            <% if employee_signed_in? %>
                <li class="nav-item <%= 'active' if current_page?(destroy_employee_session_path) %> ">
                <%= link_to t("common.sign_out"), destroy_employee_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item <%= 'active' if current_page?(new_employee_session_path) %> ">
                <%= link_to t("common.log_in"), new_employee_session_path, class: "nav-link" %>
              </li>
              <li class="nav-item <%= 'active' if current_page?(new_employee_registration_path) %> ">
                <%= link_to t("common.sign_up"), new_employee_registration_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>